spring:
  datasource:
    url: jdbc:h2:mem:kotlingrad;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
working_hours:
  start: 10
  end: 19

bot:
  about:
    for-client: Бот для записи на прием к специалисту
    master: Я мастер своего дела, самый мастеровитый из всех мастеров